### Signing up / creating new user

POST http://127.0.0.1:8000/api/user/create
Content-Type: application/json

{
    "username": "test2",
    "password": "test2test2",
    "email": "jaija.sddimil@gmail.com1"
}

###

POST http://127.0.0.1:8000/api/user/create
Content-Type: application/json

{
    "username": "test1",
    "password": "test1test1",
    "email": "jaija.ismail@gmail.com"
}

###

POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json

{
    "username": "zod2",
    "password": "t345est123"
}

###-----------------------------------------
### Updating user data

POST http://127.0.0.1:8000/api/user/update
Content-Type: application/json

{
    "user_id": 1,
    "online": 0
}

###-----------------------------------------
### Get all users

GET http://127.0.0.1:8000/api/user/get-all
Content-Type: application/json

###-----------------------------------------
### creating match entry

POST http://127.0.0.1:8000/api/match/create
Content-Type: application/json

{
    "winner": 2,
    "loser": 1,
    "game_type": 1,
    "score": "10:50"
}

###
GET http://127.0.0.1:8000/api/match/get-all?winner=2
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/match/get-all?user_id=1
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/match/get-all?loser=1
Content-Type: application/json

###

GET http://127.0.0.1:8000/api/match/get-all?loser=2
Content-Type: application/json


###
DELETE http://127.0.0.1:8000/api/match/delete?match_id=1
Content-Type: application/json

{
    "winner": 1
}




###
GET http://localhost:8000/getNotifications/


###
GET http://localhost:8000/getChats/


###
// << after getting chat_id  from API above request it heere >>
GET http://localhost:8000/getMessages/56


###
POST http://localhost:8000/invite/
Content-Type: application/json

{
    "user1": "1",
    "type": "friend",
}


###
//                 << valid for /accept/decline/deblockFriend/BlockFriend/   Api's >>
POST http://localhost:8000/accept/   
Content-Type: application/json

{
    "user2": "6",       // invitation sender u will get it with every notif 
    "type": "friend",   // <-- (friend / game)   game doesnt have a behaviour in block/deblock friend Api's
}
###
