# Generated by Django 4.2.16 on 2025-01-06 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitations',
            fields=[
                ('friendship_id', models.AutoField(primary_key=True, serialize=False)),
                ('user1', models.IntegerField()),
                ('user2', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('blocked', 'Blocked')], default='pending', max_length=8)),
                ('type', models.CharField(choices=[('game', 'Game'), ('friend', 'Friend'), ('tournament', 'Tournament')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournamentID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('tormanemnt_name', models.CharField(max_length=100)),
                ('available_players', models.IntegerField(default=0)),
                ('position1', models.PositiveIntegerField(blank=True, null=True)),
                ('position2', models.PositiveIntegerField(blank=True, null=True)),
                ('position3', models.PositiveIntegerField(blank=True, null=True)),
                ('position4', models.PositiveIntegerField(blank=True, null=True)),
                ('position5', models.PositiveIntegerField(blank=True, null=True)),
                ('position6', models.PositiveIntegerField(blank=True, null=True)),
                ('position7', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField()),
                ('msg', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.invitations')),
            ],
        ),
    ]
