filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/apache2/access.log

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
output.logstash:
  # Replace with your Logstash host and port
  hosts: ['logstash:5044']
